name: Sync Artwork

on: 
  push:
    branches: 
      - github-action-workflow-to-sync-with-google-drive

env:
  SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
  KEYFILE: ${{ secrets.KEYFILE }}
  SCOPES: ${{ secrets.SCOPES }}
  WEBSITE_IMAGES_FOLDER_ID: ${{ secrets.WEBSITE_IMAGES_FOLDER_ID }}
  SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'

      - name: Install dependencies
        run: npm install

      - name: Create env folder
        run: mkdir env

      - name: Export secret to json
        run: printf '${{ env.SERVICE_ACCOUNT }}' > env/paigewebsite-c02d0030e691.json

      - name: sync-data
        run: npm run sync