name: Webp Conversion

jobs:
  convert:
    name: Convert To webp
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
            submodules: true
            lfs: false
      
      - name: Apt Update and Upgrade
        run: |
          sudo apt update -y && sudo apt upgrade -y

      - name: Apt install
        run: sudo apt install webp -y